# Site settings
title: Bobby L. Craig
description: "Online Portfolio"
url: "https://bobbylcraig.com/"
author:
  name: "Bobby L. Craig"
  email: "bobbylcraig@gmail.com"
  url: "https://bobbylcraig.com"

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

pagination:
  per_page: 5

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-paginate

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
