site_name: "Bobby Craig | Portfolio"
site_image: /images/site-image.jpg
favicon: /images/favicon.png
description:

collections:
    projects:
        output: true
        permalink: /projects/:slug
    posts:
        output: true
        permalink: /blog/:slug

plugins:
    - jekyll-feed

social:
    -
        fa: twitter
        link: https://twitter.com/bobbylcraig
    -
        fa: linkedin
        link: https://linkedin.com/in/bobbylcraig
    -
        fa: github
        link: https://github.com/bobbylcraig
sass:
    style: compressed
    sass_dir: _sass

analytics_code: "UA-72139648-1"
