# Site settings
title: Bobby L. Craig
description: "Online Portfolio"
url: "http://www.bobbylcraig.com/"
author:
  name: "Bobby L. Craig"
  email: "bobbylcraig@gmail.com"
  url: "https://bobbylcraig.com"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
