site_name: "Bobby Craig | Portfolio"
site_image: /images/site-image.jpg
favicon: /images/favicon.png

collections:
    projects:
        output: true
        permalink: /project/:slug

plugins:
    - jekyll-feed

social:
    -
        fa: twitter
        link: https://twitter.com/bobbylcraig
    -
        fa: linkedin
        link: https://linkedin.com/in/bobbylcraig
    -
        fa: github
        link: https://github.com/bobbylcraig
    -
        fa: dribbble
        link: https://dribbble.com/bobbylcraig
    -
        fa: codepen
        link: https://codepen.io/bobbylcraig

sass:
    style: compressed
    sass_dir: _sass

analytics_code: "UA-72139648-1"
