experience:
    -
        company: Intuit
        company_link: https://intuit.com/
        title: Senior Software Engineer
    -
        company: Mailchimp
        company_link: https://mailchimp.com/
        title: Senior Software Engineer
    -
        company: Tenable
        company_link: https://tenable.com/
        title: Front-End Engineer Intern
