experience:
    -
        company: Mailchimp
        company_link: https://mailchimp.com/
        title: Software Engineer
    -
        company: Tenable
        company_link: https://tenable.com/
        title: Front-End Engineer Intern
    -
        company: Denison University
        company_link: https://denison.edu/
        title: Student Web Developer
